version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
        - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
    restart: always
    ports:
      - 8000:8000
    networks:
      - backend

  api-auth:
    container_name: api-auth
    build: api-auth
    restart: always
    ports:
      - 3001:3001
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://root:root@mongo:27017
      - JWT_SECRET=secret

  api-concerts:
    container_name: api-concerts
    build: api-concerts
    restart: always
    ports:
      - 3002:3002
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://root:root@mongo:27017
      - API_AUTH_URL=http://api-auth:3001
      - API_TICKETS_URL=http://api-tickets:3003

  api-tickets:
    container_name: api-tickets
    build: api-tickets
    restart: always
    ports:
      - 3003:3003
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://root:root@mongo:27017
      - API_AUTH_URL=http://api-auth:3001
      - API_CONCERTS_URL=http://api-concerts:3002

networks:
  backend:
    driver: bridge
